### ISSUE TITLE
Sorry, could not update profile picture

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#108]
This page : http://localhost:4200/customer-register-step1 , is not showing the updated pic once selected, after multiple refresh sometimes it shows, but still in both case while clicking "Update" button, it's giving error "Sorry, could not update profile picture" .

![2021-12-29_180051](https://user-images.githubusercontent.com/78781245/147662483-54053afb-8eb6-4fac-bb1e-c2e55274b56c.png)
![2021-12-29_180318](https://user-images.githubusercontent.com/78781245/147662656-4cea1fb1-2d1f-4086-8b5c-6638e46d58b9.png)

**Comment by kanishkavayuz** [comment]
@MaroofTech @bidyut-majumdar  i have resoved, we need to recheck with multiple testcases

**Comment by bidyut-majumdar** [comment]
> @MaroofTech @bidyut-majumdar i have resoved, we need to recheck with multiple testcases

Ask from client that they should give some access to delete the newly registered users.

For example: Lets say we are doing sign-up test  3 - 4 times to confirm it no more exists , then we need new numbers for that also, or arrange such (about 5) numbers. I will proceed with this process review again next week.
