### ISSUE TITLE
Center page doesn't have shimmers

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#110]
Center page : http://localhost:4200/center doesn't have shimmers.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  please check

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz At first page load the shimmers are disappearing before the content actually comes making the section complete white and blank with empty borders , do the needful to cover this issue.

![2022-01-07_011507](https://user-images.githubusercontent.com/78781245/148442160-9b8f858a-ced6-4a5f-8178-78527f5185a4.png)
