### ISSUE TITLE
User profile and profile menu avatar is broken

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#111]
Example URL : https://localhost:4200/customers/customer-profile

Both user profile image and profile menu avatar is broken.

![2022-01-04_003601](https://user-images.githubusercontent.com/78781245/147969654-15f84cb7-c4c9-4185-96f2-f56aec3347c2.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  this issue comes from the backend, i have reaised this issue to the client long back, still got no response from them so.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  @MaroofTech sir, if this issue (image breaks etc) remains still I will simply raise concern that VLCC WEB is not ready for demo Saturday, so please understand the priority and sort these ASAP .

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  **2 DAYS GONE . . STILL NOTHING ON THIS FUNCTIONALY BREAK . . ITS STILL NOT RESOLVED !!!**

![2022-01-07_010351](https://user-images.githubusercontent.com/78781245/148440752-2e412578-f561-4a04-a4ff-3edd542709c7.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  @MaroofTech  sir , please sort this out if we have to show video call . As this breaks over HTTPS/SSL and Video call only works over HTTPS/SSL.

So please understand the priority of this, or we have to discuss to either skip the video call process (which had to be shown though), but can't go with breaks .

**Comment by bidyut-majumdar** [comment]
On issue #174  now its breaking on HTTP also, so considering #174 as complete report, closing it .
