### ISSUE TITLE
Profile picture upload is not replacing the camera icon while choosing an image.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#112]
Example URL : https://localhost:4200/customers/customer-profile

Upon choosing an image the camera icon should be replaced with the new im
![2022-01-04_003846](https://user-images.githubusercontent.com/78781245/147969923-cedbf290-9922-4718-bf49-1e7532ad24aa.png)
age which is not happening currently.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  please check.
