### ISSUE TITLE
Notifications are not linked with Notification page.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#113]
Example URL : https://localhost:4200/customers/customer-profile

While clicking on new notifications or "view all notifications" it should be linked to Notification page.

![2022-01-04_004107](https://user-images.githubusercontent.com/78781245/147970124-475ea1e8-1b68-4346-ba75-8b29ca6503fa.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  these are linked, please recheck again

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Clicking on "View all" works, but clicking on the main notifications are not redirecting to the page .

**Comment by bidyut-majumdar** [comment]
NOTE: As per the flow in app upon clicking the "View all" it should open the notification page, and by clicking on the notification message (ex: notification of appointment booking) it should open the appointment details, or package details (if notification is for package like package renewals etc).
