### ISSUE TITLE
Display at most 3 pagination items first, which is currently 5

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#114]
Example URL : https://localhost:4200/customer/selected-category-result/Beauty

Display upto 3 pagination page.

![2022-01-04_004541](https://user-images.githubusercontent.com/78781245/147970602-dbab9c4e-4a28-464c-9e8b-8ca080d48f1e.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  it really depends on the content length, so  its predefined, so, I need to make changes(HACK) in the dependency, ill check this issue.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  check this also .

**Comment by bidyut-majumdar** [comment]
Update on table page navigation please

**Comment by bidyut-majumdar** [comment]
Need update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  im working on this.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar done
