### ISSUE TITLE
Package booking is not happening. Why ? Also remove hover effect from button in disabled state

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#117]
Example URL : [CLICK HERE](https://localhost:4200/customer/book-appointment-service/withpackage?packagedata=%7B%22selected%22:%7B%22booking_item_id%22:%221885997%22,%22ServiceName%22:%22%20Air%20Brush%20Makeup-Engagement%20Fashion%20Centre%20%22,%22ServiceCode%22:%22SRV000359%22,%22ServiceQty%22:%221%22,%22ServiceFinalAmt%22:%228499.15%22,%22ServicePaidQty%22:%221%22,%22ServiceLeftQty%22:0,%22usageper%22:100%7D,%22pdetails%22:%7B%22BookingId%22:%22945566%22,%22CenterName%22:%22TEST%20CENTER%22,%22CenterCode%22:%22INDLTEST0%22,%22ClientId%22:%22CLMC%2F21%2F18000000016292%22,%22BookingNumber%22:%22INDLTEST0PKG%2F22%2F000015%22,%22BookingDate%22:%222021-09-22%22,%22BookingExpiryDate%22:%222022-09-23%22,%22BookingQty%22:%222%22,%22BookingAmount%22:%2213498%22,%22BookingDiscountAmount%22:%221499.85%22,%22BookingAmountAfterDiscount%22:%2211998.2%22,%22BookingTaxAmount%22:%222159.67%22,%22BookingTotalAmount%22:%2214157.8%22,%22BookingTotalPaidIncTaxAmount%22:%2214158%22,%22BookingTotalPaidExcTaxAmount%22:%2211998.3%22,%22BookingTotalBalExcTaxAmount%22:%220.00000000000090949470177293%22,%22BookingUnexecutedAmount%22:%220.15%22,%22BookingExecutedAmount%22:%2211998.2%22,%22BookingBreakDays%22:0,%22PackageItemDtl%22:%5B%7B%22booking_item_id%22:%221885996%22,%22ServiceName%22:%22%20Glam%20Diva%20Fresh%20Smokey%20Glitter%20Make-up%20Look-Center%20Artist%22,%22ServiceCode%22:%22SRV000373%22,%22ServiceQty%22:%221%22,%22ServiceFinalAmt%22:%223499%22,%22ServicePaidQty%22:%221%22,%22ServiceLeftQty%22:0,%22usageper%22:100%7D,%7B%22booking_item_id%22:%221885997%22,%22ServiceName%22:%22%20Air%20Brush%20Makeup-Engagement%20Fashion%20Centre%20%22,%22ServiceCode%22:%22SRV000359%22,%22ServiceQty%22:%221%22,%22ServiceFinalAmt%22:%228499.15%22,%22ServicePaidQty%22:%221%22,%22ServiceLeftQty%22:0,%22usageper%22:100%7D%5D,%22booking_item_id%22:%221885996%22,%22ServiceName%22:%22%20Glam%20Diva%20Fresh%20Smokey%20Glitter%20Make-up%20Look-Center%20Artist%22,%22ServiceCode%22:%22SRV000373%22,%22ServiceQty%22:%221%22,%22ServiceFinalAmt%22:%223499%22,%22ServicePaidQty%22:%221%22,%22ServiceLeftQty%22:0,%22usageind%22:%22width:%2028%25%22,%22usagenum%22:72,%22expired%22:false%7D%7D)

While proceeding with the package booking I am unable to proceed with it, why ? if issue then fix it.

Also remove the hover effect from the book button while in disabled state (take help from "Get OTP" button from sign in page for classes).
![2022-01-04_010925](https://user-images.githubusercontent.com/78781245/147973040-ed757370-13c9-4630-bc56-dfa5cd6c044b.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i cannot remove the hover effect buy i have disabled the buuton, the so the button becomes pale. so

**Comment by kanishkavayuz** [comment]
the booking is working.
