### ISSUE TITLE
Fix CORS issue by 11th January anyhow ! Do whatever is needed to achieve it.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#118]
Fix this CORS issue anyhow anyway within 11th January.

Installing CORS addons, then enabling it, if it becomes disabled then uninstall it and again install to enable it back again, sorry business team or if UAT happens in-between this then none would prefer to follow these steps.

@MaroofTech sir, @kanishkavayuz close this anyway to fix this, raise tickets , share urgent mails whatever needed must be done.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i have tried my best to intimate this issue, several time, even they have aggreed that thell saolve this, im waitung for their response

**Comment by bidyut-majumdar** [comment]
Take follow-up again from them, this should be sorted anyhow anyway before my team review happens.

**Comment by bidyut-majumdar** [comment]
ArKa team will review whole VLCC at starting of next week-start from their system (heroku link), might get rejected if this CORS issue bothers them (even it bothers me).

Just advance alert.

**Comment by kanishkavayuz** [comment]
@rgnarok Sir Please escalate on this issue

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  AGAIN  NO UPDATE ON THIS . . . I have seen that without CORS issue being fixed it can't be checked from phones (whether android or iOS) , it gives error .

Since ArKa team is starting reviewing from Monday this issue should be fixed before Monday on highest priority basis.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz

**Comment by bidyut-majumdar** [comment]
Update on this ? @kanishkavayuz
