### ISSUE TITLE
Book appointment of services (centers) not happening 

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#119]
Example URL : [CLICK HERE](https://localhost:4200/customer/book-appointment-service/withclinicnservice/IFAPNLR01/%7B%22service_code%22:%22SRV0001995%22,%22service_name%22:%2220%20vials%20of%20Crescina%20HFSC%20%20%20Male%20Female%20%20%22,%22service_category%22:%22Beauty%22,%22service_sub_category1%22:%22Beauty%22,%22service_sub_category2%22:%22Products%22,%22service_type%22:%22PKG%22,%22service_app_for%22:%22General%22,%22service_status%22:%22Active%22,%22popular_center%22:%22No%22%7D)

While booking service (from center) the button is in enable state, but no price is being displayed, so unable to proceed as upon clicking "Book Appointment" its only giving warning message "Appointemnt without Price Cannot be Booked"

, solve it. Also fix the spelling.
![2022-01-04_012437](https://user-images.githubusercontent.com/78781245/147974031-720c59e4-baa0-43bb-9e8b-c1ad95a1e0e1.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar theres is a flow of center selection and service selection, in this flow, you dont need to choose the center as you have already have choosen the clinic, @bidyut-majumdar  let me know if you need clarity on the flow
