### ISSUE TITLE
Local video section is vertically duplicating itself after few mins of inactivity from other sides caller.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#120]
Example URL : https://localhost:4200/expert/video-call/5417763

Use case: After reloading the current video call page, meanwhile not connecting with the user from other end it will display the local user's Video section only once, but if no call connection happens from other side for few minutes, then its duplicating itself vertically as shown in the image.

Check and fix it.
![2022-01-03_235016](https://user-images.githubusercontent.com/78781245/147974503-571a86b4-3c46-4896-af6f-b005d92939b7.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  sort this enablex or whatever dependency it is also .

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  please recheck this issue
