### ISSUE TITLE
On Video call page all dynamic sections, buttons should be functional and working.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#121]
Example URL: https://localhost:4200/expert/video-call/5417763

On Video call page these should be functional , do whatever is needed to achieve these all :  

1. Other side user's avatar (on the above page URL it's as Ankita Roy's avatar). It should be dynamically generated, means should display experts profile avatar from client's side, and client's profile avatar from expert's side.
2. The above user's name  should be dynamically generated, means should display experts profile's name from client's side, and client's profile name from expert's side.
3. During call network disturbance the other side's user might be disconnected/offline from the call. So the status of "Online / Offline" should be in working state.
4. The call duration should be working.
5. All the buttons (enable/disable video, Mute/Unmute, Full screen, End call should be working).

Do whatever needed to achieve these all, none can be skipped.

![2022-01-04_013106](https://user-images.githubusercontent.com/78781245/147975527-b7917f9f-9da8-432b-b02b-76adb67ac0b3.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  4 and 5th can be done,123 we need to talk to the client, idon this can be done, but we will try our best 
@MaroofTech

**Comment by bidyut-majumdar** [comment]
Then please talk and sort it with client .

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  @MaroofTech  
4 and 5th are done,  
1st one is not possible, becasue we dont have the profile images of the experts 
For 2nd one i have raised an issue to the clinet 
For 3rd one, i need some help from you @bidyut-majumdar

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  if profile pic is not going then we would be using a default image these, but in any case image has to go there. 

3rd one is name, what help do you need from me ? It should be the experts/clinic's name here .

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  sorry not for third one but for full screen 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_fullscreen

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar even 3rd one sin not possible i think.

**Comment by bidyut-majumdar** [comment]
> @bidyut-majumdar even 3rd one sin not possible i think.

Why so ?

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz UPDATE ON THIS .

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz which latest issues that needs to be updated ?
