### ISSUE TITLE
Remove the dependency of using https://enablefrontend.herokuapp.com/, fix enablex issue or whatever is needed for this.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#122]
On today's  call we have seen due to some enablex issue we had to open console, then keep scrolling and search for the particular string value to be entered on https://enablefrontend.herokuapp.com/ in order to connect with the call.

Once again business or other team members won't bother to do these.

Fix these before 11th January as usual or by this Friday (7th January) with priority basis. Do whatever needed to sort this out.

![2022-01-04_014338](https://user-images.githubusercontent.com/78781245/147975853-b5703421-3a23-4789-ae7e-0baa067bd1dd.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Both Client and Expert  Appointments should match so that we can have a appointment, so that video call can happen

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz On demo day we will execute the client and expert video call from from their profile and booking table (buttons), not from 3rd party links. So sort these out too .

**Comment by bidyut-majumdar** [comment]
Putting this on "Urgent" label as well due to priority .

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  is this dependency still there ?

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  its already been resolved, we can connect through the appointments
