### ISSUE TITLE
Why both "Update" and "Continue" button is showing together on Register step 2 ?

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#125]
Example URL : https://localhost:4200/customer-register-step2

So I selected my gender and DOB and clicked update while should simply redirect me to the customer profile page, but its also displaying the "Continue" button which should not exists in case of "Step 2" page.

So fix it.

![2022-01-07_012754](https://user-images.githubusercontent.com/78781245/148443723-43d508ad-5f68-466c-acfa-5e9bb7713c0f.png)

**Comment by kanishkavayuz** [comment]
done
