### ISSUE TITLE
OTP delivery confirmation coming 2 times.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#126]
Example URL : https://localhost:4200/otp/Customer/94755xxxxx

So I logged in with my ph. no. and the OTP confirmation message is coming twice while I have not clicked re-send OTP just in case.

![2022-01-07_013352](https://user-images.githubusercontent.com/78781245/148444451-b8c004cd-9a23-4b4a-ab6b-68d010f650d7.png)

**Comment by kanishkavayuz** [comment]
done
