### ISSUE TITLE
How this expert register steps coming instead of expert profile ?

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#127]
So I entered my no for expert login , on next OTP screen entered the OTP and the next page is https://localhost:4200/expert-register-step2

Why expert register step 2 coming ? Expert should never have sign up steps , after OTP it should directly redirect the expert to expert profile  (ex: https://localhost:4200/expert/expert-profile ), redirection is not setup properly. 

![2022-01-08_221155](https://user-images.githubusercontent.com/78781245/148652530-05abec78-66ba-4312-a398-6383ccb86898.png)

**Comment by kanishkavayuz** [comment]
done
