### ISSUE TITLE
Location not working

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#129]
As we just discussed on group, reporting here as well. Location not working and showing blank.

![2022-01-10_180936](https://user-images.githubusercontent.com/78781245/148768261-cb4655d6-7cfd-469d-bd5f-6eb6c12eabe9.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz this client dependency not sorted yet. Kushagra told me yesterday client will share new API / after paying the bill.

So just pinging here to remind.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  ok, ill activate after getting new API

**Comment by bidyut-majumdar** [comment]
LOCATION DETECTION REMOVED, SO CLOSING UNTIL FURTHER NEW POINTERS COMES
