### ISSUE TITLE
Instead of checkbox use text link to differentiate the two login types

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#134]
Just like the app remove the checkbox to login as customer/expert. Instead use text links to differentiate the both login types. I have added to links vertically.

Display them with condition on the same page(to display "sign in as an expert" while signing in as a customer, or display "sign in as a customer" while signing in as an expert).

Make sure to hide the "New to VLCC? Sign up" when Expert sign in condition is active.

![1](https://user-images.githubusercontent.com/78781245/149399087-fb70d07d-5124-4402-bcb5-0c630684dda9.png)

**Comment by kanishkavayuz** [comment]
done
