### ISSUE TITLE
Please make sure right Nav-menu appears every time as it's disappearing at random times.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#135]
@kanishkavayuz  as we have seen yesterday that at random times the right navbar is not rendering , sometimes over HTTPS , sometimes over HTTP.

Please check it.

![2022-01-14_100712](https://user-images.githubusercontent.com/78781245/149452629-9d41fcba-cc65-4a83-bad7-ec07057a50b1.png)

**Comment by kanishkavayuz** [comment]
done
