### ISSUE TITLE
Button is getting disabled or remains enabled on Sign-up & Sign-in page while spinner is rotating for OTP

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#136]
@kanishkavayuz so the OTP issue (stops working at night helped me to find this one).

On login page while clicking "Get OTP" and the spinner starts rotating, the button gets into disabled state for a second before OTP screen arrives.

But on Sign up page while entering 3 details and click Sign-up, and the spinner starts rotating for a second the button doesn't get into disabled state, it remains in active state.

So please maintain active state for both scenario.

![2022-01-15_024037](https://user-images.githubusercontent.com/78781245/149587768-b96aa34e-6182-461f-8a46-617f8cf87e2b.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
Seems fine.
