### ISSUE TITLE
Book Appointment button on Book Appointment service page displays empty space at downside while there's no price 

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#137]
Demo page URL : [Click here](http://localhost:4200/customers/book-appointment-service/byclinic/%7B%22service_code%22:%22SRV0001640%22,%22service_name%22:%222X%20Whitening%20Glow%20Facial%20Treatment%20Blanc%20Precision%20%22,%22service_category%22:%22Beauty%22,%22service_sub_category1%22:%22Skin%22,%22service_sub_category2%22:%22Advanced%20Facials%22,%22service_type%22:%22PKG%22,%22service_app_for%22:%22General%22,%22service_status%22:%22Active%22,%22popular_center%22:%22No%22%7D)

Check the "Book Appointment" button, space below the button label is there while price is not being displayed, but when the empty space gets filled once the price is displayed.

![2022-01-15_032257](https://user-images.githubusercontent.com/78781245/149590525-782a4aef-87dc-433d-bdd2-188ce3eee088.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  this falls under appointment, not done yet .

**Comment by kanishkavayuz** [comment]
done

**Comment by kanishkavayuz** [comment]
![image](https://user-images.githubusercontent.com/78138350/150512624-09b9ccf1-c447-44e7-bcda-19b04ce96d18.png)

**Comment by bidyut-majumdar** [comment]
SEEMS ISSUE IS NOT APPEARING CURRENTLY
