### ISSUE TITLE
Integrate search functionality on homepage.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#139]
Integrate search functionality on the homepage, so the customer has to search the location / services manually / automatically (after clicking on detect) , and the after selection it will redirect the customer to search result page with direct result.

We just discussed this on today's standup.

![2022-01-17_094704](https://user-images.githubusercontent.com/78781245/149709381-590744ae-3487-483b-9562-fad88e517a38.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  AFTER CHOOSING CITY AND CENTER WHEN SEARCH BUTTON IS CLICKED IT SHOULD REDIRECT TO SEARCH RESULT PAGE WITH LOCATION AND CLINIC AS PRE-FILLED OPTION

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done

**Comment by bidyut-majumdar** [comment]
After taking last pull its 02:04 am night , I have not logged in and search is not functioning , entering any name in location field or in centre field displaying nothing, also centres and specialties offered sections are blank , showing nothing.

![2022-02-15_020324](https://user-images.githubusercontent.com/78781245/153942069-d65b14af-424f-45c2-ba00-a2934ef99b2a.png)

**Comment by bidyut-majumdar** [comment]
Its morning 9:10 am now, and it seems search and specialties and centre sections are appearing without logged in (which is what is has to be) .

So confirm it if showcasing search and the specialties, centre sections also depends on some API which gets disabled at night, if yes then do whatever needed to make search and the other sections functional 24 hours , causing this issue will indicate that at least at a certain period of time for few hours the homepage will remain half blank without having the search working .

**Comment by MaroofTech** [comment]
@kanishkavayuz Please take it forward

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz As we discussed in the morning that though this search is redirecting to search result page, but end result is not correct, the search result's page's both fields should be pre-filled

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i need an update on this, if its done then close
