### ISSUE TITLE
Sign in page is still accessible / visible in logged in state 

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#140]
Demo page URL : http://localhost:4200/sign-in

While in logged in state I am still able to access sign in page and all fields .

![2022-01-17_150101](https://user-images.githubusercontent.com/78781245/149744066-9ca0089e-80ba-4454-bd94-018babef167e.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i kept it on purpose because user can go to his prfile., if you log out it wont be there..

**Comment by bidyut-majumdar** [comment]
SEEMS ISSUE IS NOT APPEARING CURRENTLY, BUT THE SIGN IN PAGE APPEARS FOR A SECOND AND THEN AUTO-RELOADED TO CUSTOMER PROFILE
