### ISSUE TITLE
Upon clicking anywhere outside the notification expanded popup should be closed.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#142]
Upon clicking anywhere outside the notification expanded popup should be closed.

![2022-01-17_164509](https://user-images.githubusercontent.com/78781245/149760213-16367a54-d98a-403d-92e9-cd6d6ad9e12d.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i need some help from @MaroofTech on this.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  need to check this with @MaroofTech

**Comment by bidyut-majumdar** [comment]
Seems resolved.
