### ISSUE TITLE
When going for next page its appearing a bit scrolled down, set it to top when page opens

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#143]
Kanishka,
As you can see from the screenshot below, when I am opening a new page from previous page, its appearing as a bit scrolled down.

Please make sure page remains at top once it appears.

![2022-01-17_181619](https://user-images.githubusercontent.com/78781245/149772302-d03740dc-f35d-44d7-9d5e-6d984ac034f9.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  seems its still not implied on all pages.

**Comment by kanishkavayuz** [comment]
done , now its not gonna come down
![image](https://user-images.githubusercontent.com/78138350/150515911-d43ef36e-5468-4e21-ab2c-d13abcd72379.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  its not only to be done on one page, but on all pages, please check all the pages but clicking buttons / previous / next etc ,

**Comment by bidyut-majumdar** [comment]
SEEMS ISSUE IS NOT APPEARING CURRENTLY
