### ISSUE TITLE
Notification page is accessible without logged in.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#144]
Demo URL : http://localhost:4200/customers/notifications

This page can be accessed without being in logged in state.

![2022-01-17_193752](https://user-images.githubusercontent.com/78781245/149783393-391d1272-133c-4fc2-878a-f8d501da97dc.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
Seems sorted .
