### ISSUE TITLE
Add page animation on appointment success page.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#147]
Example page URL : http://localhost:4200/customers/AppointmentStatusSuccess/55b32c7f-4d20-426e-8

@kanishkavayuz  please add this animation on the success page, it should be applied for both video and general appointment. 

Animation effect page:  https://codepen.io/kareem-mahmoud/pen/abpamZp

Add the required JS and CSS on the success page component only, as it might not be required on anywhere else.

I will change the necessary CSS after that .

![2022-01-18_102419](https://user-images.githubusercontent.com/78781245/149873233-40b75a95-4f47-4004-988e-ebb0d9b6ea22.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz

**Comment by kanishkavayuz** [comment]
![image](https://user-images.githubusercontent.com/78138350/150522642-a095daa7-b7dc-4e7e-a72e-2067c959a860.png)
im getting this result after adding corresponding html , js ,css code from codepen

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  tried to book an appointment, came up with this warning , need to check this with you .:

![1](https://user-images.githubusercontent.com/78781245/156036281-562b5793-b30e-4907-83c5-ec3203298dd3.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar shared animation is not working as discussed over call it will be great if you shared some other one. You can also test here i have added on diffrent page http://localhost:4200/test

**Comment by bidyut-majumdar** [comment]
Not closing it due to #250  issue .

**Comment by MaroofTech** [comment]
@bidyut-majumdar as per discussion please add some awesome lotty so i am ading UI tag here

**Comment by bidyut-majumdar** [comment]
Done
