### ISSUE TITLE
Map appearance feature improvement on center page

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#148]
Example page : http://localhost:4200/customers/center

@kanishkavayuz  since GPS map is not working currently I can't check how does it look in valid state, I am attaching a screenshot , make sure we have " 'Map' and 'Satellite' " tabs as well as full screen and zoom in + zoom out options just like the following screenshots, if any additional API required or whatsoever, raise it. 

![2022-01-18_110500](https://user-images.githubusercontent.com/78781245/149877208-0ebc8e2a-0f0e-4594-a601-7cfa568ea612.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Client told us to use the stop suning GCP APIs, i think we need to remove the google maps.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz not "think" , give me direct confirmation on this from client or Kushagra (after confirming it).

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  I need confirmation on this. Contact with Kushagra (if needed), On yesterday's discussion he told me that we will still be using location detection feature (just when the client will pay the bill / share us new API key).

So , please confirm this one .

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  yes, ill update the google maps, when ill get the new API key,

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz Let me know what's the update on map locations visibility, satellite view etc ?

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Any update over map ? By when we are expecting an update from client ?

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz As of today's last email, Shivam sir said that on app GCP is completely removed,  we are going to have client call today, so ask and take confirmation there if we need to remove the map page is GCP is removed/not needed for web also .

**Comment by MaroofTech** [comment]
@bidyut-majumdar as per latest updated client want to remove GCP due to heavy billing so removed this page link

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  @MaroofTech  comment out the code of maps for now .
