### ISSUE TITLE
All notifications are taking to same appointment details page.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#149]
I have 4 notifications. But clicking this part of each notification taking me to same details section, this should be redirected to proper appt. details section

@kanishkavayuz as you stated that its API issue, please do needful.

![2022-01-18_191511](https://user-images.githubusercontent.com/78781245/149950854-182cabe2-4212-4f4f-a5c9-0658abb45768.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz Notification stuffs also belongs to part of header .

**Comment by MaroofTech** [comment]
@kanishkavayuz please check it at your end this issue its dependent on API

**Comment by bidyut-majumdar** [comment]
Hi,
if it depends on API, then please do needful to sort it out.

@kanishkavayuz  @MaroofTech

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  its wokinf fine now,, make an appointment with diffrent commecnts and different timeing , then you see the difference.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Appointment is not being booked, report linked with new issue of #194  , so not able to validate it currently with new appointment booking.

**Comment by MaroofTech** [comment]
@bidyut-majumdar its working now with new notification
