### ISSUE TITLE
Sign in and Sign up pages are still accessible in logged in state

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#150]
Sign in and Sign up pages are still accessible in logged in state

![2022-01-18_195944](https://user-images.githubusercontent.com/78781245/149956671-116bc5bd-7f94-4ba5-a3a2-266b9c26d6fc.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  need clear brefing of thisproblem

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
Seems sorted .
