### ISSUE TITLE
Its showing 1 notification only, but upon clicking one additional notification space is visible with line break

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#151]
Its showing 1 notification only, but upon clicking one additional notification space is visible with line break

![2022-01-18_200200](https://user-images.githubusercontent.com/78781245/149957271-db9b5ba3-204e-44a7-9843-7580f9328ce5.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i think it css work, please check.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz 

If there's more than one notification then the additional space doesn't exist (just like the below screenshot), while one has this spacing, so can't say its solely on CSS. Please check once again.

![nn](https://user-images.githubusercontent.com/78781245/150413522-065b2b73-505c-4497-893c-f722ef01b664.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  we need to connect for tjis.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar it has specified hight ibn the class, since its has the space, even we need to have that class in the zer notification

**Comment by MaroofTech** [comment]
![Screenshot from 2022-02-11 15-49-01](https://user-images.githubusercontent.com/78342064/153574763-69719bd7-fc22-41be-ab52-47406a36c45c.png)
![Screenshot from 2022-02-11 15-48-40](https://user-images.githubusercontent.com/78342064/153574777-2e12f1fe-6ea9-4101-b8aa-abfd732786f6.png)

@bidyut-majumdar  check this issue one is when i reduced height other is at default height
