### ISSUE TITLE
Why its showing "add profile picture" warning message on OTP verification screen after filling OTP

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#153]
Why its showing "add profile picture" warning message on OTP verification screen after filling OTP ? Please remove.

![2022-01-18_233051](https://user-images.githubusercontent.com/78781245/149993240-6224607d-0316-45e0-8158-9da4577a7f6d.png)

**Comment by kanishkavayuz** [comment]
removed

**Comment by bidyut-majumdar** [comment]
sems sorted
