### ISSUE TITLE
After landing on register step 2 its showing warning message of gender and DOB addition while I have not started it yet.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#154]
Example URL : http://localhost:4200/customers/customer-register-step2

After landing on register step 2 its showing warning message of gender and DOB addition (along with success message) while I have not started it yet. Please remove the message on landing.

![1](https://user-images.githubusercontent.com/78781245/149994120-2cf85ba3-9352-4c4f-9b4f-579578aabc11.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  warning removed

**Comment by bidyut-majumdar** [comment]
seems sorted .
