### ISSUE TITLE
I signed up using a name, email address. But not reflecting on customer profile once landed after sign up done

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#155]
I signed up using a name, email address. But not reflecting on customer profile once landed after sign up done

![2022-01-18_234553](https://user-images.githubusercontent.com/78781245/149995270-850abbeb-c318-4011-b875-c048e1961eb1.png)

**Comment by bidyut-majumdar** [comment]
Also I thin the "First Name" field was changed earlier to "Full Name" , so change it as well.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  need to report to this to client

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
it was major issue, seems sorted currently.
