### ISSUE TITLE
Profile pic upload on register step 1 is not being reflected on step 2 in profile menu

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#157]
Upon new sign up and then uploading profile pic upload on register step 1 is not being reflected on step 2 in profile menu automatically while it should, its requiring page refresh to make the image appear, please fix it.

![1](https://user-images.githubusercontent.com/78781245/149997339-a3b94d6c-1ccf-46af-9c6f-2a92be371bb0.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz seems after your change on this the the 2nd sign-up page first loads with first attached screenshot, then it automatically reloads again with 2nd screenshot.

This first breaking the elements (on first load), then again auto-loading breaking the experience.
Please find better alternative to this, or just reload the page at first step so that it doesn't show the broken element and then again reloads itself.

![8 search better idea than page reloading](https://user-images.githubusercontent.com/78781245/150411837-73ddb32b-f228-41a4-b9ef-82a7d98f7e3f.png)

![3 page reloading twice](https://user-images.githubusercontent.com/78781245/150411866-324c491b-dac9-4caf-880b-dd46234d8acc.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
As reported on the #178 now this page even doesn't come as after OTP we enter directly to step2, not step1 .

So can't validate this issue to be fixed .

**Comment by MaroofTech** [comment]
after step one step2 is coming please check now @bidyut-majumdar

**Comment by bidyut-majumdar** [comment]
@MaroofTech I tested with latest code pull . . new sign up  - - - entered OTP - - landed on STEP2 instead of STEP1  (so did not get chance to upload any DP ).

**Comment by bidyut-majumdar** [comment]
CLOSING
