### ISSUE TITLE
If there's no notification, then please show "No new notification" on this empty space.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#159]
If there's no notification, then please show "No new notification" on this empty space.

![2](https://user-images.githubusercontent.com/78781245/150411628-926db3b2-dcee-43c5-b4e3-63ccb90efe69.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i have hidden the notification  icon while registration,

**Comment by bidyut-majumdar** [comment]
Seems we have removed the notification from step2. Fine .

Sorted then .
