### ISSUE TITLE
Please welcome with customers name instead of their number.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#160]
While during sign up it welcomes with "Hi Bidyut Majumdar !" message for customer.

It seems during sign in its welcoming both customer and expert with their phone number "Hi 9475xxxxxx !" instead of their full name while they have already full-name available for their profile, please correct it.

![4 I already have nane](https://user-images.githubusercontent.com/78781245/150412816-72ea1555-c5fa-4205-b539-1828a456ac63.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  For signed in users we will get the details after otp verification , before that there is no possible way for getting the name, thtast the bets soltion that can be done, but again its a client dependent so i need to ask for them,

**Comment by bidyut-majumdar** [comment]
Ok, ask for it.

I will re-think on this pointer .

**Comment by MaroofTech** [comment]
@kanishkavayuz you can show name taking from signup page

**Comment by bidyut-majumdar** [comment]
Seems this has been sorted as couldn't find the issue .
