### ISSUE TITLE
Invoice view details not working

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#161]
Invoice view details not working, upon clicking it should display invoice view details page.

![10 invoice view details not working](https://user-images.githubusercontent.com/78781245/150418034-c0451758-3f15-4b98-9e42-3967a236dbe5.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done

**Comment by bidyut-majumdar** [comment]
This seems working (so closing it) , but back button not redirecting properly , so reported on #184
