### ISSUE TITLE
Seems this OTP lagging or not coming issue still there

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#162]
@kanishkavayuz  I believe this falls under client dependency.

This was happening 2 weeks back also , last week, even today. Same screenshot for console

![2022-01-21_020043](https://user-images.githubusercontent.com/78781245/150417664-f12568ba-07cd-4e6c-baf3-43424da370ec.png)
![14 this sudden OTP lagging issue still exists](https://user-images.githubusercontent.com/78781245/150417796-ee02327c-7afd-4b3c-a259-8e302d33020d.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar   i will raise this concern  with client again

**Comment by bidyut-majumdar** [comment]
This report is same as #184  with more detailing on newer report .

**Comment by bidyut-majumdar** [comment]
Since its reported better way in #180  , closing it .
