### ISSUE TITLE
After clicking Book Appointment it takes around 15 second to open payment page.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#163]
After clicking Book Appointment it takes around 15 second to open payment page, or sometimes even longer.

I'm not sure if its client dependency or what. Please check @kanishkavayuz 

![11 about 15 seconds wait time before payment window comes](https://user-images.githubusercontent.com/78781245/150418414-0e512603-e373-4d0b-81ed-a6acb3ad7227.png)

**Comment by kanishkavayuz** [comment]
the payment page is dependen upon the two servers,so it will take some time

**Comment by bidyut-majumdar** [comment]
Since there are change on the app flow recently ("Pay at centre" and "Pay online"), this flow will have changes as well. So keeping it opened with note of self-reminding (to remind myself)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Update on the payment gateway delay response please.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Updated,and you know the sattus of this issue
