### ISSUE TITLE
Please put package validity expire bar on these pages also.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#164]
Please put package validity expire bar on these pages also, just adding screenshot of the pages.

![12 please put validity expiry bar here also](https://user-images.githubusercontent.com/78781245/150418773-f565f6f5-ef72-413a-b604-ccb97f82fb78.png)
![13 please put validity expiry bar here also](https://user-images.githubusercontent.com/78781245/150418784-93abd6b5-4330-4bba-a968-5dff51588695.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done

**Comment by bidyut-majumdar** [comment]
Seems sorted .
