### ISSUE TITLE
Hide notification options during Sign in / Sign up / OTP pages.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#166]
As we discussed earlier on this, please hide notification options during Sign in / Sign up / OTP pages.

This to be implied both for customer (sign in, sign up, otp, step 1, step 2) and expert (sign in, otp) pages.

![2 - Hide notifications from sign in , sign uo, otp pages](https://user-images.githubusercontent.com/78781245/151225449-efa42aa3-7234-4a3c-8a3f-d028f357e944.png)

**Comment by kanishkavayuz** [comment]
done.

**Comment by bidyut-majumdar** [comment]
Ok, Notification has been removed from OTP and Sign in steps pages.
