### ISSUE TITLE
On the Sign up OTP page replace the sign in, sign up button with the menu options of step 1

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#167]
So I have signed up with new details, on OTP screen I am still getting sign up and sign in buttons an top right menu, please replace them with the menu items of register step 1 .

![3 - On sign up OTP screen please replace the sign in up buttons with first step menu items](https://user-images.githubusercontent.com/78781245/151225873-632b3ef3-8d6a-4509-abf0-03f598717ba6.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar without entering the otp how can he acess the register1 and page

**Comment by bidyut-majumdar** [comment]
No more required .
