### ISSUE TITLE
Step jumping to customer profile from register step 1 giving broken image

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#168]
So I was on sign up step 1 , I did not upload the avatar , but since profile menu was appearing I clicked on profile setting and landed on customer profile page, but with broken image (it's not even on SSL error one), please use the current default user image in these cases.

![4 - step jumping to customer profile from register step 1 giving broken image](https://user-images.githubusercontent.com/78781245/151226303-ab1925ae-4ea3-4cc1-af89-e3826889649b.png)

**Comment by kanishkavayuz** [comment]
done, i have added the dummy image, if theres isn nor profile picture
![image](https://user-images.githubusercontent.com/78138350/152806057-cd419e77-b4f4-4546-8797-31125c3c1723.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  but now images are breaking for connection over HTTP as well, (reported on #174 ), so can't validate it.

**Comment by MaroofTech** [comment]
@bidyut-majumdar  if there is no image then default image will show so close this issue for image break issue #174 already in place which is client dependent

**Comment by bidyut-majumdar** [comment]
This issue is also bit part of #177  ,  so can't close unless image comes here (after break is fixed)

**Comment by bidyut-majumdar** [comment]
Means without fulfilling (report #177 ) STEP2 no one should enter any other internal page, while opening any internal page it should redirect to STEP2 page .

Just like on other website if we are at step 2 of a registration process of  lets say total 5 steps, then whenever we try to open any page which requires registration it asks to complete the registration flow first.

**Comment by MaroofTech** [comment]
@bidyut-majumdar for this flow we need to track current path of user in db and need API changes @kanishkavayuz please take it forward

**Comment by bidyut-majumdar** [comment]
Ok, so be it then.

@kanishkavayuz  please do needful (raise ticket / ask client/ report) by today .

**Comment by MaroofTech** [comment]
@bidyut-majumdar  If register step 1 is done and we leave the paltform ,and  again signin then after otp register step 2 will come you can check by this number 8745029280 it has already step 1 done

**Comment by bidyut-majumdar** [comment]
Closing it as its now fulfilling #177
