### ISSUE TITLE
Update this avatar upload function

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#169]
As a part of UI enhancement I have added another avatar upload UI this time, previous code still there , please match and update the avatar upload function on the new one (comment out the older one after this), please test once also after done.

![5 - update this avatar upload function](https://user-images.githubusercontent.com/78781245/151226845-14cfbf56-dcff-4b2a-9943-8ab2b246f82b.png)

**Comment by kanishkavayuz** [comment]
i have added the avatar UI, but cannot render the image in the UI, even i have added the jquery function to make it work,

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  though step1 page is not coming now (as reported on #178  ), Also please take @MaroofTech sir's help if needed , avatar should be uploaded this way only , same for on customer profile (where you said you commented out the new code).

This way of avatar upload is going on app as well.

**Comment by MaroofTech** [comment]
@bidyut-majumdar its added and working but if old image is already there then image broken issue will appear and you can't see avtar image. you can check it by new account or commenting check

**Comment by bidyut-majumdar** [comment]
This issue is linked with #178 , we are now landing directly on STEP2 , even by manually editing the link and entering the STEP1 link directly it is still redirecting us to STEP1 , so I'm not able to validate this report .

**Comment by bidyut-majumdar** [comment]
CLOSING
