### ISSUE TITLE
Update the  avatar upload function on customer & expert profile

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#170]
Just like the issue #169 , please update the avatar update functionality on the customer profile page also, code is already there , just replace the ID's and classes (I  couldn't do it myself), please note that earlier it was in the "Profile settings" tab with a confirmation about successful avatar upload.

So please comment out the code in the "Profile setting" avatar upload section as we are directly doing this now, the success confirmation should come on this .

For Expert profile, since experts can't update their avatar please put the same code here, just remove the input function, camera icon's code from there.

![6 - update this avatar upload function](https://user-images.githubusercontent.com/78781245/151233361-03db577d-3cfe-4eaa-8439-0458e1a5c2ee.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i have added the new design but if i click on that allover new  profile UI, im not able to open the file/folder dialog box 
![image](https://user-images.githubusercontent.com/78138350/152786884-fe07fb64-47ad-40ef-aa9f-e3e462674ac9.png)

**Comment by bidyut-majumdar** [comment]
Please make it functional , take @MaroofTech  sir or any other's help.

Also on our call you said that you commented out the code of avatar upload on left sidebar of customer profile, please make it live and functional as well.

Avatar should be uploaded directly after choosing. no need to click "Upload photo" .

**Comment by bidyut-majumdar** [comment]
Closing it as no more happening.
