### ISSUE TITLE
No profile menu or other options appearing on Expert profile.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#171]
I guess it happened after the notification click issue was sorted, anyway - somehow the header menu (profile menu, no, notifications etc) not appearing for expert profile. Please check on urgent basis

![2022-01-27_010738](https://user-images.githubusercontent.com/78781245/151234374-c37d1c44-37c7-4fec-98ea-4127fcc0ef46.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar can you tell me when are you getting teh above issue
![image](https://user-images.githubusercontent.com/78138350/152741485-3a42bd5a-cafb-430a-9f28-6496ad4bc9f1.png)
![image](https://user-images.githubusercontent.com/78138350/152741530-3d309f73-e8a3-4fec-8903-1eecc8bb91b1.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz if its not happening at your end you can push code , I will take pull and re-check to confirm the issue's existence .

**Comment by kanishkavayuz** [comment]
ok.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  code pushed please check.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i need to check on this issue

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz 

After taking pull right now my header is still like this :

![2022-02-14_101012](https://user-images.githubusercontent.com/78781245/153801135-5b7e6944-574a-4eea-b4fd-0583f12c0913.png)

**Comment by bidyut-majumdar** [comment]
Closing it as no more happening.
