### ISSUE TITLE
Customer register step1 and step2 is accessible for visitors without being logged in / sign up

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#176]
Example URL:

http://localhost:4200/customers/customer-register-step2
http://localhost:4200/customers/customer-register-step1

Both links are accessible for visitors without being logged in or trying to sign up.

**Comment by MaroofTech** [comment]
@bidyut-majumdar  these are steps before signup. hence they can access without logged in and sign up.

**Comment by bidyut-majumdar** [comment]
@MaroofTech  STEP1 and STEP2 page required first sign up fulfilling and then OTP input, only then STEP1 , STEP2 page comes, but a visitor lets say directly opening STEP1 (avatar upload page) = he will find blank details. Open it on incognito, you will understand.

**Comment by bidyut-majumdar** [comment]
@MaroofTech as discussed over call today, please check on this .
