### ISSUE TITLE
Profile and all other pages are accessible without fulfilling sign up step2

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#177]
The user can go till sign up step 2 , and then without fulfilling the details and then update they can directly visit internal links, means they can access all other pages. which also gives weird results in profile page with warnings like "Please select valid Date of Birth" and age as 2022 years etc.

Please make sure if they don't fill and update the sign up step 2, if they try to access any internal page - they will be redirected to back on sign up step2

![2022-02-14_012348](https://user-images.githubusercontent.com/78781245/153772289-e6964f12-e885-48e9-8d57-8bdd89245eb0.png)

**Comment by bidyut-majumdar** [comment]
Closing it as no more happening

**Comment by bidyut-majumdar** [comment]
This issue came back upon my current test again .

![2022-02-23_195243](https://user-images.githubusercontent.com/78781245/155338007-5d2320c3-a1c0-48e2-8a1a-fa9b7bba61ee.png)

**Comment by MaroofTech** [comment]
#226 is same as 177
