### ISSUE TITLE
During sign up after entering its taking directly to sign up step2 instead of step1 which asks to update profile picture

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#178]
During sign up after entering its taking directly to sign up step2  ( http://localhost:4200/customers/customer-register-step2 ) instead of step1 which asks to update profile picture ( http://localhost:4200/customers/customer-register-step1 ) ,

This was not happening earlier, please fix it, also the avatar upload placeholder image seems to be breaking as well.

![2022-02-14_012820](https://user-images.githubusercontent.com/78781245/153772441-ecf52bde-ad77-401a-b25d-36b58e4af358.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  if the first step has been done then it will ask directly ask you to go for 2nd step ok, the user  should not go for first step, correct me if im wrong
@MaroofTech

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  seems you did not get the report here.

After entering OTP during sign up the user should go to STEP1, not STEP2 .

So I don't need to be get corrected here. Try one sign up yourself first .

**Comment by bidyut-majumdar** [comment]
@MaroofTech sir, this is still happening after taking evening pull , I signed up - - next entered OTP - - STEP 2 window appeared (instead of STEP1 ) .

**Comment by bidyut-majumdar** [comment]
Tested last night at 1:24 am as well as right now 9:15 am , while new sign up - - entered OTP - - landed on STEP2 page instead of STEP1 again .

![2022-02-15_091600](https://user-images.githubusercontent.com/78781245/153988935-cbccbf17-31bd-4af5-8a74-71187e10ce2d.png)

**Comment by bidyut-majumdar** [comment]
Took latest pull . . . Did new sign up with random digits - - Entered OTP - - Its finally landed on STEP2 , not STEP1 . . Please check the video, the STEP2 is actually passing through STEP1, but STEP1 is appearing for a blink and then its immediately auto redirected to STEP2 . Might be some redirect config issue.



So please check the video (at the point of redirection specifically) to understand. Until further review next morning, this pointer remaining opened now.

Video shared on teams group

**Comment by bidyut-majumdar** [comment]
Tested once again right now, same result .

**Comment by bidyut-majumdar** [comment]
CLOSING
