### ISSUE TITLE
Add new category images to respective category

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#181]
So we know we now have 18 categories, I have created all separate images for those 18 categories , please add them accordingly, so it appears on all other pages as well.

Also I found duplicate categories like "Skin care" and "Skin Care" , "Hair reduction" and "Hair Reduction".

Please consult with relevant team about these duplication as it makes completely no sense (just with some capitalized case), also please put then as Sentence case (just like it used to be)

Moreover I found some weird categories like "Advance Appliances" . Why and Who will go for booking such weird meaningless categories ? Please ask the relevant team to give clarity on this.

![153718624-10119918-4409-46aa-b11d-50133c6ed847](https://user-images.githubusercontent.com/78781245/153773769-e24bd45a-d109-47b4-accd-b6dcde3c4044.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Please update me about category images and what about duplicated category ?

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  since there are multiple repeated category and some category are capitalised and some are not, so it should resolve at the client end, after resolve illadd the images.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz taken follow up from client ?

**Comment by bidyut-majumdar** [comment]
Need update, please proceed with images that  I have shared already  @kanishkavayuz

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  its a client dependent for now, ill work on after this https://github.com/VAYUZ-VLCC/vlcc-api-issues/issues/237 gets resolved

**Comment by bidyut-majumdar** [comment]
ok
