### ISSUE TITLE
Customer profile's sidebar popular categories are not clickable and also please put to limit to display only upto 5 category.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#182]
Customer profile's sidebar popular categories are not clickable and also please put to limit to display only up to 5 categories.

Just make all those categories clickable to redirect to respective category details page, put limitation to display only up to 5 categories.

With a "View all" button below the sidebar widget to redirect them to search result of category page.

**Comment by bidyut-majumdar** [comment]
Just adding image for reference 

![2022-02-14_103617](https://user-images.githubusercontent.com/78781245/153803456-9c9736e7-f958-4218-b238-913238a44b25.png)

**Comment by bidyut-majumdar** [comment]
This issue should be fixed on category details page's sidebar part as well.

**Comment by MaroofTech** [comment]
@kanishkavayuz  what changes made in flow please check why not clickable and for limit in both module done from my end

**Comment by bidyut-majumdar** [comment]
@MaroofTech Please check it again, though limitation is set, but I did not require "More" to load more result, but "View all" to redirect to search result page. Please also replicate the limitations etc on appointment details page sidebar.
