### ISSUE TITLE
Please add the functional code for search location and search center with result below

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#186]
Please add the functional code for search location and search center with result below as showcased in the screenshot, put the same card's code on other required pages wherever its needed to be placed.

![2022-02-14_111210](https://user-images.githubusercontent.com/78781245/153806775-93392dd3-ad07-424f-8143-012ada62d0ca.png)

**Comment by bidyut-majumdar** [comment]
Please update on this search result page also

**Comment by kanishkavayuz** [comment]
done
