### ISSUE TITLE
Need Some help with the CSS

### ISSUE THREAD

**Issue by kanishkavayuz** [MaroofTech/vlcc-web-issue-tracker#188]
![image](https://user-images.githubusercontent.com/78138350/153822103-2e15897d-ba2c-4865-9c0e-e73067665b5e.png)

Since this clinic search Form  module is going in 3 to 4 components so please add the the Required CSS to make it look good so it dosent get disturebed in any modue

**Comment by bidyut-majumdar** [comment]
fixed

**Comment by MaroofTech** [comment]
@kanishkavayuz close it if its done
