### ISSUE TITLE
Please do some allignment

### ISSUE THREAD

**Issue by kanishkavayuz** [MaroofTech/vlcc-web-issue-tracker#189]
![image](https://user-images.githubusercontent.com/78138350/153854642-465e4d01-93b0-461c-b1d9-f7d04ce7c374.png)

@bidyut-majumdar  As i have added the input field for filteresing services, please do some alignemnt for the same

**Comment by MaroofTech** [comment]
@bidyut-majumdar any update on this? If its done please close
