### ISSUE TITLE
Homepage loading a broken image and ask client for HD rectangular images for homepage banners

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#195]
Though profile menu image breaks has sorted, homepage is loading a broken image - please sort it and ask for HD images, ask client for it .

![Though profie menu image breaks has sorted, homepage is loading a broken image, also please ask for HD images](https://user-images.githubusercontent.com/78781245/154194447-07918b10-e099-40db-869a-5aab38e58693.png)

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz take follow up from client on this tomorrow .

**Comment by MaroofTech** [comment]
@bidyut-majumdar broken link image is filtered and for HD rectangular images for homepage banners its dependent on client will resolve when client will done
