### ISSUE TITLE
Add the session type functionality on clinic details page and search inside clinic specialities

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#198]
Add the session type functionality on clinic details page and search inside clinic specialties as we discussed earlier, also add the clinic profile detail's older UI's code to the newer one, delete the older one's code.

![2022-02-16_095002](https://user-images.githubusercontent.com/78781245/154195682-b23f2660-6b99-49da-9912-a7f193fd728c.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done
