### ISSUE TITLE
Counting on customer and expert profile's appointment table

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#201]
As feedback was shared on these please do the followings:

1. Showcase the "Upcoming" first with the count
2. Then confirmed appointment/ video consultation with the count , add new table row for it with the required functionality to display confirmed appointments only, this should be on both appointment and video consultation tabs.
3. Then Past appointment / Video consultation with the count (in place of history)
4. Remove all other tab (ex: history)

![2022-02-16_111749](https://user-images.githubusercontent.com/78781245/154204153-76a93905-12ee-4a9f-a6dd-eb2563cac36a.png)

**Comment by bidyut-majumdar** [comment]
@MaroofTech one conflict I've found on this, I will discuss today .

**Comment by MaroofTech** [comment]
@bidyut-majumdar done code pushed to github
