### ISSUE TITLE
No video appealing even having camera mic permissions enabled

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#205]
So in this scenario I left the call , re-joined as customer. My camera and mic permission is enabled. But camera is inactive, no video appearing, neither mine, nor from the other side (in this case @kanishkavayuz )

![OVER HTTPS WITH PERMISSIONCUSTOMER S CAMERA INACTIVE, NO VIDEO APPEARING](https://user-images.githubusercontent.com/78781245/154249137-a9a952ce-c55a-4915-b55b-cdbd1d78b489.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  please update on this issue

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz lets have video call test tomorrow to close it .
