### ISSUE TITLE
Camera and pic permission prompt is not coming from both customer and experts end.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#206]
So we (customer (me) and @kanishkavayuz  (expert) ) have have browser history, cache, cookies, site permissions cleaned up).
Joined the video call , the permission prompt for camera and mic access did not come. Kept waited for 6 - 8 mins, did not come.
Then interchanged our account and checked on this too, but same result. Prompt no coming.

![2022-02-16_155412](https://user-images.githubusercontent.com/78781245/154249604-c75dd454-2907-44d9-85d6-6c48e7ee5da3.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Please update the latest issue or the update

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz video call test needed for closing it .
