### ISSUE TITLE
Linking error on Appointment details page when clicking Package details button and popular services categories

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#208]
Linking error on Appointment details page when clicking Package details button and popular services categories

1. On appointment details page, the "view buttons" on Packages is not clickable.
2. On appointment details page, clicking any option from sidebar's Popular category / View service button taking us to broken/blank page.
![2022-02-18_002109](https://user-images.githubusercontent.com/78781245/154550669-fad83ee5-4629-44d7-855a-5f22ea914f63.png)

**Comment by kanishkavayuz** [comment]
done

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz the first point "On appointment details page, the "view buttons" on Packages is not clickable." is not working still, while the sidebar linking is working .

**Comment by bidyut-majumdar** [comment]
need update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done
