### ISSUE TITLE
Please set the notification page functions that we discussed earlier

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#209]
Please set the notification page functions that we discussed earlier just like invoice listing page, should be applied for both expert and customer.

![2022-02-18_002312](https://user-images.githubusercontent.com/78781245/154551040-057d8bdc-19d8-4cc7-9148-f6da28baa052.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar  done from my side please fix the ui and close the issue
