### ISSUE TITLE
Please check and apply solution for page specific component CSS being applied on another page 

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#210]
Please check and apply solution for page specific component CSS being applied on another page while it should not, we have discussed it already and sent you a message for a similar reference.

![2022-02-18_002624](https://user-images.githubusercontent.com/78781245/154551471-caea2f92-d47d-4584-89b7-89db50fc7415.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar  issue fixed please check it, as we discussed and add css by this refrence
