### ISSUE TITLE
Notification popup came while notification is already turned on

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#211]
This was tested on heroku,

While opening the website it asked at first for notification, I turned yes .

While sign in , and then along with OTP send message it also showed "enable notification" message.

While this notification message should come when notification prompt has not come or was checked "no" etc condition, please remove reminding this was while notification is already active
![2022-02-21_133546](https://user-images.githubusercontent.com/78781245/154913662-23186cf3-ac6f-48e4-9380-3e3bec2c42da.png)
 .

**Comment by bidyut-majumdar** [comment]
![2022-02-23_091105](https://user-images.githubusercontent.com/78781245/155258178-bcc7708e-5949-4e5d-b9f8-2eda972b0514.png)

**Comment by bidyut-majumdar** [comment]
Need update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  im working on this today
