### ISSUE TITLE
Add shimmers when specialties are being loaded on clinic details page.

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#212]
When changing appointment type its only showing search box, no other hint that something is being loaded.

Please apply same on other search pages (if any) as well where its taking time to load the results.

![2022-02-21_1239d25](https://user-images.githubusercontent.com/78781245/154924854-74beb633-dd8b-49e7-8559-9339f19c4005.png)

**Comment by bidyut-majumdar** [comment]
Update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done

**Comment by bidyut-majumdar** [comment]
Example URL : [CLICK HERE](http://localhost:4200/customers/clinic-details?clinicdata=%7B%22clinicdata%22:%7B%22center_code%22:%22INUPAGR01%22,%22center_name%22:%22AGRA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22B%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%222ND%20FLOOR,%20RAJENDRA%20POINT,%20M.G.%20ROAD,(NEAR%20BHAGAT%20HALWAI)%22,%22address_line3%22:%22%22,%22area_name%22:%22SANJAY%20PLACE%22,%22city_name%22:%22AGRA%22,%22state_name%22:%22UTTAR%20PRADESH%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(0562)%202527295%2F%207320%22,%22center_map%22:%22https:%2F%2Fbit.ly%2F3iZOcNQ%22,%22center_latitude%22:%2227.20097%22,%22center_longitude%22:%2278.003589%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D%7D)

Can not see any shimmer here

**Comment by MaroofTech** [comment]
@bidyut-majumdar there is one error that causes search input open i fixed it and also added no data find layout. Now flow is smmoth so i adding reveiw-required

**Comment by bidyut-majumdar** [comment]
@MaroofTech , the above mentioned [URL](https://localhost:4200/customers/clinic-details?clinicdata=%7B%22clinicdata%22:%7B%22center_code%22:%22INUPAGR01%22,%22center_name%22:%22AGRA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22B%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%222ND%20FLOOR,%20RAJENDRA%20POINT,%20M.G.%20ROAD,(NEAR%20BHAGAT%20HALWAI)%22,%22address_line3%22:%22%22,%22area_name%22:%22SANJAY%20PLACE%22,%22city_name%22:%22AGRA%22,%22state_name%22:%22UTTAR%20PRADESH%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(0562)%202527295%2F%207320%22,%22center_map%22:%22https:%2F%2Fbit.ly%2F3iZOcNQ%22,%22center_latitude%22:%2227.20097%22,%22center_longitude%22:%2278.003589%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D%7D)
is accessible for visitors, without logged in state, please sort this too .

**Comment by MaroofTech** [comment]
@bidyut-majumdar  above URL is not clickabl anyhow for clinic details page url[http://localhost:4200/customers/clinic-details?clinicdata=%7B%22clinicdata%22:%7B%22center_code%22:%22INUPAGR01%22,%22center_name%22:%22AGRA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22B%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%222ND%20FLOOR,%20RAJENDRA%20POINT,%20M.G.%20ROAD,(NEAR%20BHAGAT%20HALWAI)%22,%22address_line3%22:%22%22,%22area_name%22:%22SANJAY%20PLACE%22,%22city_name%22:%22AGRA%22,%22state_name%22:%22UTTAR%20PRADESH%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(0562)%202527295%2F%207320%22,%22center_map%22:%22https:%2F%2Fbit.ly%2F3iZOcNQ%22,%22center_latitude%22:%2227.20097%22,%22center_longitude%22:%2278.003589%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D%7D](url) check is already added for without signin can't be access
