### ISSUE TITLE
This search result message is not dynamic yet, and should be visible only after some selection

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#213]
This search result message is not dynamic yet, and should be visible only after some selection

![2022-02-21_145747](https://user-images.githubusercontent.com/78781245/154926764-d9746826-49fc-4d78-a8ac-62251f478298.png)

**Comment by bidyut-majumdar** [comment]
update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  ill work on it today.
