### ISSUE TITLE
Video consultation for clinic details showing no specialities

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#217]
Example URL : [CLICK HERE](http://localhost:4200/customers/clinic-details?clinicdata=%7B%22clinicdata%22:%7B%22center_code%22:%22INUPAGR01%22,%22center_name%22:%22AGRA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22B%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%222ND%20FLOOR,%20RAJENDRA%20POINT,%20M.G.%20ROAD,(NEAR%20BHAGAT%20HALWAI)%22,%22address_line3%22:%22%22,%22area_name%22:%22SANJAY%20PLACE%22,%22city_name%22:%22AGRA%22,%22state_name%22:%22UTTAR%20PRADESH%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(0562)%202527295%2F%207320%22,%22center_map%22:%22https:%2F%2Fbit.ly%2F3iZOcNQ%22,%22center_latitude%22:%2227.20097%22,%22center_longitude%22:%2278.003589%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D%7D)

CHECK IT TOO. WAITED A MIN IN CASE IT LOADS FROM API, IT DID NOT .

![2022-02-21_231957](https://user-images.githubusercontent.com/78781245/155005596-fa54355b-fa69-419e-b183-cefc1c0e43f6.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar data is not coming from API at code level its fine i checked it by adding static data of video type. You can check it once data will come

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Please we need to connect for this issue discussiom as it is in the clinet hold
