### ISSUE TITLE
Video consolation via category search booking ending up as general appointment booking 

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#219]
Video consolation via category search booking ending up as general appointment booking 

Seems appointment filter doesn't work.

Example URL : [CLICK HERE](http://localhost:4200/customers/selected-category-result/Beauty?searchdata=%7B%22location%22:%22%22%7D)
![2022-02-22_021224](https://user-images.githubusercontent.com/78781245/155023919-d79d6bd8-f38d-479e-886b-cd2c9a341e7e.png)

Book appt. service details page also showing booking type as "General appointment" : 
Example URL : [CLICK HERE](http://localhost:4200/customers/book-appointment-service/withclinicnservice?searchdata=%7B%22location%22:%22NEW%20DELHI%22,%22center%22:%7B%22center_code%22:%22INDLDEL24%22,%22center_name%22:%22DELHI%20DWARKA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22A%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%22101,%201ST%20FLOOR,%20HL%20WINGS,%20PLOT%20NO%202,%20POCKET-4,%20SEC-11,%20DWARKA,%22,%22address_line3%22:%22%22,%22area_name%22:%22DWARKA%22,%22city_name%22:%22NEW%20DELHI%22,%22state_name%22:%22DELHI%20-%20NCR%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(011)%2040618986%2F28042877%2F8%20%2F%208744051952%22,%22center_map%22:%22https:%2F%2Fgoo.gl%2FPaZzCC%22,%22center_latitude%22:%22%22,%22center_longitude%22:%22%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D,%22service%22:%7B%22ServiceCode%22:%22SRV000385%22,%22service_name%22:%22AHA%20Manicure%22,%22service_category%22:%22Beauty%22,%22service_sub_category1%22:%22%22,%22service_app_for%22:%22General%22,%22service_status%22:%22Active%22,%22popular_center%22:%22No%22,%22service_gender%22:%22%22,%22ServicePrice_id%22:%2230400%22,%22ServicePrice%22:%22849%22,%22PriceList%22:%22A%22,%22ServiceType%22:%22RBS%22,%22ClientDiscountPercentage%22:%2225%22,%22EmpDiscountPercentage%22:%2250%22,%22CGST%22:%229%22,%22SGST%22:%229%22,%22ServiceValidity%22:%221%22%7D%7D)

Landed on checkout page : 
Example URL : [CLICK HERE](http://localhost:4200/customers/checkout?checkoutdata=%7B%22checkoutdata%22:%7B%22clinic%22:%7B%22center_code%22:%22INDLDEL24%22,%22center_name%22:%22DELHI%20DWARKA%22,%22center_type%22:%22COCO%22,%22center_ratelist%22:%22A%22,%22address_line1%22:%22VLCC%20HEALTH%20CARE%20LIMITED%22,%22address_line2%22:%22101,%201ST%20FLOOR,%20HL%20WINGS,%20PLOT%20NO%202,%20POCKET-4,%20SEC-11,%20DWARKA,%22,%22address_line3%22:%22%22,%22area_name%22:%22DWARKA%22,%22city_name%22:%22NEW%20DELHI%22,%22state_name%22:%22DELHI%20-%20NCR%22,%22country_name%22:%22INDIA%22,%22phone_number%22:%22(011)%2040618986%2F28042877%2F8%20%2F%208744051952%22,%22center_map%22:%22https:%2F%2Fgoo.gl%2FPaZzCC%22,%22center_latitude%22:%22%22,%22center_longitude%22:%22%22,%22center_pic%22:%22https:%2F%2Flms.vlccwellness.com%2Fapi%2FDSC_8517.JPG%22,%22center_status%22:%22Active%22,%22popular_center%22:%22No%22%7D,%22date%22:%222022-02-24%22,%22time%22:%2210:22%20AM:00%22,%22service%22:%7B%22ServiceCode%22:%22SRV000385%22,%22service_name%22:%22AHA%20Manicure%22,%22service_category%22:%22Beauty%22,%22service_sub_category1%22:%22%22,%22service_app_for%22:%22General%22,%22service_status%22:%22Active%22,%22popular_center%22:%22No%22,%22service_gender%22:%22%22,%22ServicePrice_id%22:%2230400%22,%22ServicePrice%22:%22849%22,%22PriceList%22:%22A%22,%22ServiceType%22:%22RBS%22,%22ClientDiscountPercentage%22:%2225%22,%22EmpDiscountPercentage%22:%2250%22,%22CGST%22:%229%22,%22SGST%22:%229%22,%22ServiceValidity%22:%221%22%7D,%22type%22:%22RBS%22,%22price%22:%22849%22,%22Appointmentdata%22:%7B%22device_id%22:%2288c50512-ee53-4d92-9612-d6cdb09bca86%22,%22auth_token%22:%22fae4eb7f766e188d6c289a68fc6eef156b0c1cb2c64566ed65f3c33a90babaf8%22,%22client_mobile%22:%229475552277%22,%22center_code%22:%22INDLDEL24%22,%22service_type%22:%22RBS%22,%22service_code%22:%22undefined%22,%22client_name%22:%22Bidyut%20Majudmdar%22,%22client_emailid%22:%22Bidyut.vayuz@gmail.com%22,%22client_gender%22:%22Male%22,%22att_doc%22:%22undefined%22,%22appointment_comment%22:%22%22,%22appointment_time%22:%2210:22%20AM:00%22,%22appointment_type%22:%22%22,%22appointment_date%22:%222022-02-24%22%7D,%22sessiondate%22:%222022-02-21T20:47:12.207Z%22%7D%7D)

![2022-02-22_021918](https://user-images.githubusercontent.com/78781245/155024607-b35223e3-fb85-4171-b26d-b3d635fdea60.png)

This one showing "Pay at centre" button,  which is not part of Video consultation page.

**Comment by bidyut-majumdar** [comment]
update

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  I need to recheck the Filter functionality for the issue, but as of now, there are no video appointments coming up in the API, It's also a  Client Dependency.

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz issue raised to client ?

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar The issue has been intimated to client  by Kushgra sir, so i have made few  required changes please check

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  kushagra sir has made initimated the issue to the client like yesterday, but issue has raised,
I have added check for the video consultaion

**Comment by bidyut-majumdar** [comment]
Same video consultation issue . As video consultation flow is paused due to API issue, I can't check the status of it.
