### ISSUE TITLE
Sign up / Profile

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#226]
In case i am clicking back on completing the sign up it is taking back to the last sign up step it is incorrect

**Comment by MaroofTech** [comment]
need to manage user login path(State) in backend. to redirect where he left @rgnarok

**Comment by bidyut-majumdar** [comment]
@MaroofTech  , seems client dependency as you raised concern about it.

**Comment by bidyut-majumdar** [comment]
Closing it on behalf of @rgnarok
