### ISSUE TITLE
View all button should be hidden is there's no package

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#231]
1. On customer profile beside the "Active package" the "View all" button should be hidden is there's no package (neither active , nor expired).
2. This section should only display active packages only, if there's no active package then it should show the current  "no package found" animation with the "View all" button in visible state so that customer can go and visit all packages page.

![2022-02-23_084702](https://user-images.githubusercontent.com/78781245/155256500-7d0e1e05-3845-46a5-85e8-54b3dbc4a582.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  ill work on it today

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done

**Comment by bidyut-majumdar** [comment]
I have latest code pull,

but still point no. 2 seems to be not implemented :

![7](https://user-images.githubusercontent.com/78781245/155587133-5e758e51-e4be-40a2-9283-cf5d2cd831f1.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done , please check at you phon  number
