### ISSUE TITLE
OTP entering on Expert login not showing notification warning instead

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#232]
OTP entering on Expert login not showing notification warning instead, my notification is already on and entered OTP is correct , this test was done over HTTPS,

After entering OTP its showing notification message instead of logging in.

![2022-02-23_091337](https://user-images.githubusercontent.com/78781245/155258502-58c902f9-9391-4e2f-976f-ecc2d85e934d.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  notification functionality remove and issue will be resolved

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  i have commented code for the notification, this should be working fine without notification, please check ovr the HTTPS, as well as HTTP
