### ISSUE TITLE
Clicking on "View details" on Package card for both customer profile section and package listing doesn't work sometime

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#236]
Clicking on "View details" on Package card for both customer profile section and package listing doesn't work sometime , attaching a screenshot (of package listing page) which shows that upon clicking its trying to open an URL, but not opening at end.

![2022-02-24_013450](https://user-images.githubusercontent.com/78781245/155400203-ae692675-1b9c-40b4-a483-f8de3ef84403.png)
![2022-02-24_013936](https://user-images.githubusercontent.com/78781245/155400211-05c65eb3-fc0d-4615-ac65-174363ebd1ba.png)
package

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  done.
