### ISSUE TITLE
Opening customer profile displaying repeated notifications of blank left out fields annoyingly .

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#240]
Opening customer profile from any other page displaying repeated notifications of blank left out fields annoyingly .

This kind of notification should display only once at first (if left blank) just to remind people that something is empty, remining this way repeatedly also with duplicated notification messages are annoying.

![5](https://user-images.githubusercontent.com/78781245/155584750-ef9dd85a-1f06-47dd-82cf-8069c29d1bf0.png)

**Comment by MaroofTech** [comment]
@kanishkavayuz i commented all toast message in other components please don't open
