### ISSUE TITLE
Where is the appointment type filter gone on selected category result page ?

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#241]
Example URL : [CLICK HERE](http://localhost:4200/customers/selected-category-result/Beauty?searchdata=%7B%22location%22:%22%22%7D)

This page used to have appointment type filter (general or video), I checked the code, its there, but its not visible on page.

![6](https://user-images.githubusercontent.com/78781245/155586741-74cb4940-178f-4e39-9039-f31620ee1088.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  it will popup  after the services getiing loaded.
