### ISSUE TITLE
On local HTTPS OTP is not being accepted on Expert login

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#242]
So as per our (me and Kanishka's call on 24th Feb's evening, I ran local on HTTPS, tried to login as expert , while entering OTP it did not accept , displayed some sort of error on console, @kanishkavayuz  stated he would check this , adding screenshots,

More over while entering the last digit of OTP, its triggering the notification message every time, so please check these , adding screenshot of this also. 

![2022-02-24_181039](https://user-images.githubusercontent.com/78781245/155587748-01529eb5-d5dc-43d0-bda1-2ea72f732028.png)

![2022-02-24_181110](https://user-images.githubusercontent.com/78781245/155587769-0dadfc56-95d3-41af-8e8d-204730fee49b.png)

![2022-02-24_181213](https://user-images.githubusercontent.com/78781245/155587980-09ae6b6e-277e-4667-a9ee-5260a83dc401.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  im removing  firebase notification, this issue should be resolved

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  removed push notification, this should work fine
