### ISSUE TITLE
One's video is not appearing to other one on Video consultation

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#244]
So on 24th Feb's evening I (customer) and @kanishkavayuz (expert)  tested it , we joined video call.

But we could see our own videos , but not other one's . Means neither I could see Kanishka's face, nor Kanishka could see mine.

@kanishkavayuz stated its related to someenablex issue and he would be checking this .

![2022-02-24_183509](https://user-images.githubusercontent.com/78781245/155589791-94916411-8d8e-467c-ad1b-c5ad9d09b6a3.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  I rechecked on this issue, it's quite working fine, well connect on this issue to recheck, maybe due to some network issue at EnableX side, we were not able to connect on the respective checking day.

**Comment by bidyut-majumdar** [comment]
![2022-02-28_220113](https://user-images.githubusercontent.com/78781245/156020833-af6ed174-a093-4bad-848c-76c14b3620ae.png)


This still exist .

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz I will connect with you first on tomorrow standup to validate this issue's clearance .
