### ISSUE TITLE
On category details page no services are being displayed

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#245]
Example URL : [CLICK HERE](http://localhost:4200/customers/selected-category-result/Beauty?searchdata=%7B%22location%22:%22%22%7D)

As discussed with @MaroofTech today on standup call, while choosing location and center its not displaying any serviced , neither for general appointment , nor for video consultation.

![9](https://user-images.githubusercontent.com/78781245/155655023-76f4e075-e9ea-466b-8224-632e319fc950.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  its a API Issue, cuurently on hold so, the functionality has been added gfor filtereing genral nad the video consultaiion .

**Comment by bidyut-majumdar** [comment]
Ok, if its API issue , then once API issue is sorted I will check this again to validate the issue's existence . Till then this report will remain opened .

**Comment by bidyut-majumdar** [comment]
Since this is API issue, we don't have any pending action here it seems .
