### ISSUE TITLE
Add placeholder "Phone Number" on the phone field for both sign up and sign in page

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#253]
Earlier it was there , but after the new NPM with country flag installed the placeholder is only visible when we click inside the field, but when the page loads or we click outside of the field , the placeholder is not visible .

Please check for solution on the npm package to display placeholder by default too.

![2022-03-03_113320](https://user-images.githubusercontent.com/78781245/156506753-b7d185af-90c0-4e52-b8ed-a184f7386e29.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar its css issue please check at your end

**Comment by bidyut-majumdar** [comment]
Fixed it
