### ISSUE TITLE
Add cropping feature while uploading image

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#258]
So on last Demo Saturday it was suggested by Tej sir that while uploading an image it should show cropping option too .

 
![2022-03-06_233339](https://user-images.githubusercontent.com/78781245/156935891-a5d43abd-4cf9-4637-8c67-6b4caeed9bef.png)

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar added all the features of cropping please do the UI work , code pushed
![image](https://user-images.githubusercontent.com/78138350/157500904-f6c81742-29c2-4e5f-8439-29834eb0f903.png)
