### ISSUE TITLE
Email and city field on expert profile

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#262]
As per app Email and city field is going on expert profile , I have added the fields, please add the functional code there .

![1](https://user-images.githubusercontent.com/78781245/157174332-9d8e1540-5073-4538-9d91-35e2570142cc.png)

**Comment by MaroofTech** [comment]
@bidyut-majumdar @kanishkavayuz email and city is not coming in expert profile data i checked with Shikhar as well @kanishkavayuz please check API and update key name here so that we can proceed further

**Comment by bidyut-majumdar** [comment]
@MaroofTech Please comment out the code , since not relevant I am closing this .
