### ISSUE TITLE
When Popular Specialities more than 9-10 Ui will look ugly how we will handle this ?

### ISSUE THREAD

**Issue by MaroofTech** [MaroofTech/vlcc-web-issue-tracker#27]

**Comment by bidyut-majumdar** [comment]
This sidebar section is only for limited no of results (ex: max 8) . If we are not displaying top specialties (as got to know there's no API for such) then there's only another option to display max 8 results there with a "Browse all" button at footer which will redirect to all specialty result  . . The title "Popular specialty" also to be renamed as just "specialty" then .
