### ISSUE TITLE
Profile >> Not able to change image

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#271]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/85341053/157394665-2580d84a-656e-457f-b0fd-fc3f05037f89.png">

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  Please make the UI work on Centering the Crop Ill add the Functionality

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  I have not seen the crop in action yet , what to center then ?

**Comment by bidyut-majumdar** [comment]
And I will need both rotate and crop functionality what is going on app .
