### ISSUE TITLE
Pay u

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#281]
IN case i am clicking on back it is taking me to transaction fail then i am stuck it must take me to check out page

**Comment by kanishkavayuz** [comment]
@rgnarok  let me know which back button you are trying to go back with the click since there are two back buttons, one is with chrome back button, please provide the clarity with an illustration

**Comment by rgnarok** [comment]
@kanishkavayuz  i am using the back of Pay U not the browser
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/157426097-ac79aeea-8ee7-4207-99c5-ba9c376ea5d5.png">

**Comment by kanishkavayuz** [comment]
@rgnarok  we don't have the control of that button, its in the PayU Predefined route, if it gets clicked then transaction will fail

**Comment by bidyut-majumdar** [comment]
Closing it as stated by @kanishkavayuz  with the reason mentioned above.
