### ISSUE TITLE
In case i made the payment then i am stuck it is not taking me to appointment request sent booking screen

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#282]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/157406958-94b99d61-6d77-45e4-9cf1-ff2255a0a2b8.png">

**Comment by bidyut-majumdar** [comment]
This is happening on WEB from today morning .

**Comment by kanishkavayuz** [comment]
@rgnarok  Sir, unexpected issue, I need to discuss with @technicalbirdVayuz  on this so, no timeline for this
