### ISSUE TITLE
Booking PAckage

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#287]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/157428578-f31d44d8-d37f-40f9-a810-5b74a33dc7b8.png">

Remove this price not available

**Comment by MaroofTech** [comment]
@kanishkavayuz please have a look its related to booking flow

**Comment by kanishkavayuz** [comment]
ok.
