### ISSUE TITLE
Booking package

### ISSUE THREAD

**Issue by rgnarok** [MaroofTech/vlcc-web-issue-tracker#288]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/157429346-5a8dd7f2-d04b-48a8-bc22-8a8297b3338e.png">
Remove option to pay as i am booking from package it must give option to book appointment

**Comment by MaroofTech** [comment]
@kanishkavayuz Please check this pointer it has dependency over payment gateway

**Comment by kanishkavayuz** [comment]
ok ill check it
