### ISSUE TITLE
Read notifications are not clickable while notifications under unread and all are clickable

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#291]
Read notifications are not clickable while notifications under unread and all are clickable, please apply this for same customer and expert profile .

![2022-03-10_083130](https://user-images.githubusercontent.com/78781245/157580301-9e8d138a-a9f3-4565-84d4-ad91ae032d26.png)

**Comment by bidyut-majumdar** [comment]
@MaroofTech not happening still .

**Comment by MaroofTech** [comment]
@bidyut-majumdar same logic is applied over read and unread earlier on read id is diffrent that i fixed, you can check it by any new notification

**Comment by MaroofTech** [comment]
@bidyut-majumdar got the issue and fixed please check
